# Generated by Django 4.2.3 on 2023-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
